name: qitcoin_flutter_app
description: "Qitcoin Core Official Multi-Platform Cross-Chain Wallet & Bridge"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  provider: ^6.1.1
  http: ^1.2.0

flutter:
  uses-material-design: true
