# Qitcoin Node 3 (Wallet / Block Explorer Peer)
regtest=1
server=1
listen=1
txindex=1

rpcuser=qtcadmin
rpcpassword=secure_qtc_password_2026
rpcport=39332
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

port=39333
bind=0.0.0.0

addnode=node1:39333
addnode=node2:39333
